# Generated by Django 3.2.2 on 2021-05-10 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_art'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='arts',
            field=models.ManyToManyField(to='main_app.Art'),
        ),
    ]
