# Generated by Django 3.2.2 on 2021-05-10 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_artist_arts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='arts',
            new_name='art',
        ),
    ]
