# Generated by Django 3.2.2 on 2021-05-10 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_rename_arts_artist_art'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='art',
        ),
        migrations.AddField(
            model_name='artist',
            name='art',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.art'),
            preserve_default=False,
        ),
    ]
