# Generated by Django 3.2.2 on 2021-05-10 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20210510_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='art',
        ),
        migrations.AddField(
            model_name='artist',
            name='art',
            field=models.ManyToManyField(to='main_app.Art'),
        ),
    ]
