# Generated by Django 3.2.2 on 2021-05-11 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20210510_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='painting',
        ),
        migrations.AddField(
            model_name='photo',
            name='artist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.artist'),
            preserve_default=False,
        ),
    ]
